# Generated by Django 4.2 on 2023-04-07 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='test',
            field=models.TextField(null=True),
        ),
    ]
